### ISSUE TITLE
`unpkg.co` is a typo in code?

### ISSUE THREAD

**Issue by dogfuntom** [segundofdez/segundofdez.com#1]
The line: https://github.com/segundofdez/segundofdez.com/blob/1b5d289b1dc848c8d56671ece1f6a1cc098c053d/src/_includes/layouts/default.vto#L36

See also:
> I do not own unpkg.org or unpkg.co. They are owned by a malicious 3rd party who copied the site and put it up hoping to steal some traffic.
> —https://github.com/mjackson/unpkg/issues/78#issuecomment-354309219

**Comment by segundofdez** [comment]
Thank you very much. fixed
bc1826e76c287008aa2c49c487abc29c157124ac
